#!/usr/bin/env sh
# To eject an external HDD
# TODO: Does it work? Maybe I should use hdparm -y instead

if which udisksctl
then
  sudo umount "$1" && sudo udisksctl power-off -b "$1"
else
  echo "udisks is necessary to eject. Run nix shell nixpkgs#udisks"
  exit 1
fi


