#!/usr/bin/env sh
# To eject an external HDD

if which udisksctl
then
  sudo umount "$1" && sudo udisksctl power-off -b "$1"
else
  echo "udisks is necessary to eject. Run nix shell nixpkgs#udisks"
  exit 1
fi


