#!/usr/bin/env sh
# To eject an external HDD
# TODO: This should be a nix-script so I can add the dependencies

if which hdparm
then
  sudo umount "$1" && sleep 2 && sudo hdparm -y "$1"
else
  echo "hdpark necessary to eject. Run nix shell nixpkgs#hdparm"
  exit 1
fi


