#!/usr/bin/env sh
# To eject an external HDD
# TODO: Does it work? Maybe I should use hdparm -y instead

if which hdparm
then
  sudo umount "$1" && sudo hdparm -y "$1"
else
  echo "hdpark necessary to eject. Run nix shell nixpkgs#hdparm"
  exit 1
fi


