#!/usr/bin/env bash
# $1: Name of the service account to use, e.g. `admin-user`

kubectl -n kubernetes-dashboard get secret $(kubectl -n kubernetes-dashboard get "sa/$1" -o jsonpath="{.secrets[0].name}") -o go-template="{{.data.token | base64decode}}"
