#! /usr/bin/env bash
# rename files in $EDITOR

file_name=$(basename "$1")
file_path=$(realpath "$1")
file_dir=$(dirname "$file_path")

# create a file with the name of the file being edited as contents
temp=$(mktemp)
trap 'rm $temp' EXIT
echo "$file_name" >> "$temp"

# bring the editor to the user to give the new name
"$EDITOR" "$temp"
new_name=$(cat "$temp")

# actually rename the original file
old_path=$file_path
new_path="$file_dir/$new_name"

if [ "$new_path" != "$old_path" ]; then
  mv "$file_path" "$file_dir/$new_name"
fi
