#!/usr/bin/env bash
set -euo pipefail

function get_field() (
  field=$(jq -r --arg l "$2" '.fields[] | select(.label == $l) | .value' <<< "$1")
  echo "$field"
)

keys_ids=$(op document list --format json | jq -r '.[] | select(.tags[]? | contains("ssh-key")) | .id')

echo "Found $(wc -l <<< "$keys_ids") keys:" 

for uuid in $keys_ids
do
  item=$(op item get "$uuid" --format json)
  file_name=$(jq -r '.files[0].name' <<< "$item")
  echo "* $file_name"

  # Download them if they are not in ~/.ssh
  file_location="$HOME/.ssh/$file_name"
  if [ -f "$file_location" ]
  then
    printf "\t Is already in the .ssh folder\n"
  else
    printf "\t It's not locally available. Downloading it...\n"
    op document get "$uuid" >> "$file_location"
    chmod 0600 "$file_location"
  fi

  # Add them to the agent
  public_key=$(get_field "$item" "public key")
  if ssh-add -L | grep -q "$public_key"
  then
    printf "\t It's already in the agent\n"
  else
    printf "\t It's not in the agent. Adding it... \n"
    passphrase=$(get_field "$item" "passphrase")
    expect << EOF
      log_user 0
      spawn ssh-add -t8h "$file_location"
      expect "Enter passphrase"
      send "$passphrase\n"
      expect eof
EOF
  fi
done


