#!/usr/bin/env bash
# Retrieve versions of a package from maven central, ordered from newest to oldest
# TODO: Also for nexus, npm?
# TODO: Take -n«number of versions to show?»

IFS=$'\n'

function maven_central() (
  path="$(echo "$1" | tr "." "/")"
  index="$(curl -sL "https://repo.maven.apache.org/maven2/$path/" \
    | grep "</a>" \
    | grep -v "metadata" \
    | grep -v ">../<"
    )"

  for line in $index; do
    version="$(echo "$line" | grep -Po "<a.*?>\K.*?(?=/</a>)")"
    date="$(echo "$line" | grep -Po "\d\d\d\d-\d\d-\d\d \d\d:\d\d")"
    date_as_epoch="$(date -d "$date" +%s)"
    echo "$date_as_epoch $version"
  done
)

# Actual response
ordered_versions="$(maven_central "$1" | sort -nr | cut -d ' ' -f 2)"

# This is all just to print the first match in bold green
readarray -t ordered_versions_array <<< "$ordered_versions"

for i in "${!ordered_versions_array[@]}"; do
  version="${ordered_versions_array[$i]}"
  if [ "$i" -eq 0 ];
  then
    echo -e "\033[1;32m$version\e[0m"
  else
    echo "$version"
  fi
done
